export const runtime = "nodejs";

import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { Resend } from "resend";

// ------------------------------------------------------------
// SAFE RESEND CLIENT
// ------------------------------------------------------------
let resend: Resend | null = null;

if (process.env.RESEND_API_KEY) {
  resend = new Resend(process.env.RESEND_API_KEY);
} else {
  console.warn("⚠️ RESEND_API_KEY missing — email sending disabled");
}

// ------------------------------------------------------------
// SAFE EMAIL SENDER
// ------------------------------------------------------------
async function sendSimpleAlertEmail(to: string) {
  if (!resend) return;
  if (!to || !to.includes("@")) return;

  try {
    await resend.emails.send({
      from: "GoTrade Alerts <alerts@gotrade.one>",
      to,
      subject: "🚀 New Trade Alert",
      html: `
        <div style="font-family: Arial, sans-serif; padding: 20px; background: #f7f7f7;">
          <div style="max-width: 480px; margin: auto; background: #ffffff; padding: 24px; border-radius: 12px; border: 1px solid #e5e5e5;">
            
            <h2 style="color: #111; margin-top: 0; font-size: 22px;">
              🚀 New Trade Alert Detected
            </h2>

            <p style="font-size: 15px; color: #333; line-height: 1.5;">
              A new trading signal has just been generated by your GoTrade bot.
            </p>

            <p style="font-size: 15px; color: #333; line-height: 1.5;">
              Log in to your dashboard to view the full trade details, charts, and bot status.
            </p>

            <a href="https://www.gotrade.one/dashboard"
               style="display: inline-block; margin-top: 20px; padding: 12px 18px; background: #4f46e5; color: #fff; text-decoration: none; border-radius: 8px; font-weight: bold;">
              Open Dashboard
            </a>

            <p style="font-size: 13px; color: #777; margin-top: 24px;">
              You are receiving this alert because you have active notifications enabled in your GoTrade account.
            </p>

          </div>
        </div>
      `,
    });
  } catch (err) {
    console.error("EMAIL SEND ERROR:", JSON.stringify(err, null, 2));
  }
}


// -----------------------------
// BOT ROW IDs
// -----------------------------
const EURUSD = {
  tradeTable: "EURUSD_trades_state",
  barTable:   "EURUSD_bar_state",
  newsTable:  "EURUSD_news_state",
  tradeRow: "5726f12d-46d7-4e03-8131-a1febfd7ae42",
  barRow:   "87b8c55f-52c7-4824-9fc7-98febbbdb02d",
  newsRow:  "d1c4f448-a9f9-4938-ac75-14398ee7aa40"
};

const ETH = {
  tradeTable: "ETHUSDT_trades_state",
  barTable:   "ETHUSDT_bar_state",
  newsTable:  "ETHUSDT_news_state",
  tradeRow: "0fee5c83-f233-4487-bc5f-f7e703a14024",
  barRow:   "530ef4a6-e3be-4c19-b34e-1d84062170cb",
  newsRow:  "40d28923-8f43-464f-8147-244d63141587"
};

const RELAX = {
  tradeTable: "SWING_trades_state",
  barTable:   "SWING_bar_state",
  newsTable:  "SWING_news_state",
  tradeRow: "81587010-c8c1-4857-a1e8-f476aa04c439",
  barRow:   "f5d39010-88a3-4b9c-9e3d-eb3bc2c2ce71",
  newsRow:  "9d5488a8-fefb-4df3-96f7-6347cf1ade87"
};

// -----------------------------
// BOT ROUTER
// -----------------------------
function getBotTables(bot: string | null | undefined) {
  if (!bot) return RELAX;
  const b = String(bot).trim().toUpperCase();
  if (b === "EURUSD") return EURUSD;
  if (b === "ETH" || b === "ETHUSDT") return ETH;
  if (b === "RELAX" || b === "SWING") return RELAX;
  return null;
}

// -----------------------------
// HELPERS
// -----------------------------
function sanitizeString(v: unknown) {
  if (v === null || v === undefined) return null;
  return String(v).replace(/[\u0000-\u001F\u007F]/g, "").trim();
}

function normalizeSide(s: unknown) {
  if (!s) return "flat";
  const v = String(s).toLowerCase();
  if (v === "buy") return "long";
  if (v === "sell") return "short";
  if (["long", "short", "flat"].includes(v)) return v;
  return "flat";
}

function isFiniteNumber(v: unknown) {
  const n = Number(v);
  return Number.isFinite(n);
}

// -----------------------------
// MAIN HANDLER
// -----------------------------
export async function POST(req: Request) {
  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );

  const raw = await req.text();
  let body: any;

  try {
    body = JSON.parse(raw);
  } catch {
    return NextResponse.json({ ok: false, error: "invalid JSON" }, { status: 400 });
  }

  const type = String(body.type ?? "").toLowerCase();
  const botKey = body.bot ?? "relax";
  const tables = getBotTables(botKey);

  if (!tables) {
    return NextResponse.json({ ok: false, error: "unknown bot" }, { status: 400 });
  }

  // ------------------------------------------------------------
  // TRADE UPDATE
  // ------------------------------------------------------------
  if (["entry_long", "entry_short", "sl", "tp"].includes(type)) {
    if (!isFiniteNumber(body.entry) || !isFiniteNumber(body.stop) || !isFiniteNumber(body.tp)) {
      return NextResponse.json({ ok: false, error: "invalid numeric values" }, { status: 400 });
    }

    const payload = {
      type: sanitizeString(body.type),
      side: normalizeSide(body.side),
      ticker: sanitizeString(body.ticker),
      entry: Number(body.entry),
      stop: Number(body.stop),
      tp: Number(body.tp),
      timestamp: new Date().toISOString()
    };

    await supabase
      .from(tables.tradeTable)
      .update(payload)
      .eq("id", tables.tradeRow);

    // ------------------------------------------------------------
    // MULTI-USER EMAIL LOGIC
    // ------------------------------------------------------------
    let planColumn = null;

    if (botKey.toUpperCase() === "RELAX" || botKey.toUpperCase() === "SWING") {
      planColumn = "plan_PRO_BUNDLE";
    } else if (botKey.toUpperCase() === "EURUSD") {
      planColumn = "plan_EURUSD";
    } else if (botKey.toUpperCase() === "ETH" || botKey.toUpperCase() === "ETHUSDT") {
      planColumn = "plan_ETHUSDT";
    }

    if (planColumn) {
      const { data: users } = await supabase
        .from("profiles")
        .select("*")email")
        .eq(planColumn, true);

      if (users && users.length > 0) {
        for (const u of users) {
          if (u.email) await sendSimpleAlertEmail(u.email);
        }
      }
    }

    return NextResponse.json({ ok: true, status: "trade updated" });
  }

  // ------------------------------------------------------------
  // BAR UPDATE
  // ------------------------------------------------------------
  if (type === "bar") {
    const payload = {
      ticker: sanitizeString(body.ticker),
      high: isFiniteNumber(body.high) ? Number(body.high) : null,
      low: isFiniteNumber(body.low) ? Number(body.low) : null,
      timestamp: new Date().toISOString()
    };

    await supabase
      .from(tables.barTable)
      .update(payload)
      .eq("id", tables.barRow);

    return NextResponse.json({ ok: true, status: "bar updated" });
  }

  // ------------------------------------------------------------
  // NEWS / SWING META UPDATE
  // ------------------------------------------------------------
  if (type === "news" || type === "swing_news" || type === "swing_meta") {
    const payload: any = {
      timestamp: new Date().toISOString()
    };

    if (type === "news") {
      payload.news_today = Boolean(body.news_today);
      payload.news_message = sanitizeString(body.news_message);
      payload.next_news_time = sanitizeString(body.next_news_time);
      payload.news_window_active = Boolean(body.news_window_active);
      payload.news_countdown = isFiniteNumber(body.news_countdown)
        ? Number(body.news_countdown)
        : null;
    }

    if (type === "swing_news" || type === "swing_meta") {
      payload.ticker = sanitizeString(body.ticker);
      payload.entry_window_text = sanitizeString(body.entry_window_text);
      payload.entry_window_percent = isFiniteNumber(body.entry_window_percent)
        ? Number(body.entry_window_percent)
        : null;
      payload.hold_duration_text = sanitizeString(body.hold_duration_text);
      payload.risk_window_note = sanitizeString(body.risk_window_note);
    }

    await supabase
      .from(tables.newsTable)
      .update(payload)
      .eq("id", tables.newsRow);

    return NextResponse.json({ ok: true, status: "news updated" });
  }

  return NextResponse.json({ ok: false, error: "unknown alert type" }, { status: 400 });
}
